### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by vperilla** [neoclide/neovim#1]
When I clone this repository and execute
sudo npm install -g

get this error
npm ERR! path /usr/lib/node_modules/.staging/@chemzqm/neovim-2608fd3d/node_modules/event-lite
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@chemzqm/neovim-2608fd3d/node_modules/event-lite' -> '/usr/lib/node_modules/.staging/event-lite-d96d8773'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-03T07_52_09_156Z-debug.log

**Comment by chemzqm** [comment]
It's problem of your npm, it uses yarn by default, so use `yarn install` to install dependencies.

**Comment by vperilla** [comment]
I just installed, but after installation thats ok, then :checkhealht on neovim
show me not installed
## Node.js provider (optional)
  - INFO: Node.js: v11.15.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

**Comment by chemzqm** [comment]
It has nothing to do with coc.nvm
